on: push
jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/lambda/java:11.2024.06.05.12-arm64
    steps:
      - run: yum install -y curl # curl, gitのインストールによって証明書がインストールされる可能性を否定する調査をしていないのでテストの偽陰性が高まることに注意
      - run: curl --http2 -v https://api.sandbox.push.apple.com
  openssl:
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/lambda/java:11.2024.06.05.12-arm64
    steps:
      - run: yum install -y openssl
      - run: openssl s_client -connect api.sandbox.push.apple.com:443
  pure:
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/lambda/java:11.2024.06.05.12-arm64
    steps:
      - run: ls /var/lang/lib/security/cacerts
      - run: keytool -list -keystore /var/lang/lib/security/cacerts
